name: skolyozmobil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  uuid: ^3.0.6
  provider: ^6.0.5
  flutter_animate: ^4.2.0
  intl: ^0.19.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  fl_chart: ^0.65.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  syncfusion_flutter_gauges: ^28.2.7
  badges: ^3.1.2
  flutter_local_notifications: ^18.0.1
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.1
  flutter_blue_plus: ^1.5.0
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1 # ✅ App icon generation
  flutter_native_splash: ^2.4.0    # ✅ Splash screen generation

flutter:
  uses-material-design: true

  assets:
    - assets/scoli_logo.png
    - assets/boypp.png
    - assets/girlpp.png

flutter_icons:
  android: true
  ios: true
  image_path: "assets/scoli_logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#000000"
  image: assets/scoli_logo.png
  android: true
  ios: true
  android_gravity: center
  ios_content_mode: center
