name: skolyozmobil
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  page_transition: ^2.2.1
  provider: ^6.0.5
  flutter_animate: ^4.2.0
  google_fonts: ^6.1.0
  http: ^1.2.0
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  syncfusion_flutter_gauges: ^28.2.7
  flutter_blue_plus: ^1.5.0 # Check for the latest version
  permission_handler: ^11.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/scoli_logo.png
    - assets/boypp.png
    - assets/girlpp.png